[package]
name = "esparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.2"
nom = "7.1.2"

[dev-dependencies]
assert2 = "0.3.7"
test-case = "2.2.2"
